# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend_proto/frontend_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&frontend_proto/frontend_messages.proto\x12\x11sims_ims_frontend\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"-\n\x0c\x43lientAction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\r\n\x05param\x18\x02 \x01(\t\"\x10\n\x0e\x41\x63tionApprovedb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_proto.frontend_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=61
  _LOGINREQUEST._serialized_end=111
  _TOKEN._serialized_start=113
  _TOKEN._serialized_end=135
  _CLIENTACTION._serialized_start=137
  _CLIENTACTION._serialized_end=182
  _ACTIONAPPROVED._serialized_start=184
  _ACTIONAPPROVED._serialized_end=200
# @@protoc_insertion_point(module_scope)
