# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import frontend_messages_pb2 as frontend__messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontend.proto\x12\x07SimsIMS\x1a\x17\x66rontend_messages.proto2\x82\x01\n\x0cSimsFrontend\x12\x33\n\x08\x43redAuth\x12\x15.SimsIMS.LoginRequest\x1a\x0e.SimsIMS.Token\"\x00\x12=\n\tClientCmd\x12\x15.SimsIMS.ClientAction\x1a\x17.SimsIMS.ActionApproved\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMSFRONTEND._serialized_start=53
  _SIMSFRONTEND._serialized_end=183
# @@protoc_insertion_point(module_scope)
